CREATE TABLE public."keep-alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NULL DEFAULT ''::TEXT,
  random UUID NULL DEFAULT gen_random_uuid (),
  CONSTRAINT "keep-alive_pkey" PRIMARY KEY (id)
);

INSERT INTO public."keep-alive"(name)
VALUES
  ('placeholder'),
  ('example');

ALTER TABLE public."keep-alive" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select" ON public."keep-alive" FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public."keep-alive" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete" ON public."keep-alive" FOR DELETE USING (true);
